#!name=Locket Gold VietCongChuas
#!desc=Mở khoá premium cho ứng dụng Locket Widget

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26.3; Scale/3.00)

[Script]
# ~ Enhanced for Shadowrocket, Surge, & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/VietCongChuas/LocketDiamond_Free/main/locketfix_fixfree.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/VietCongChuas/LocketDiamond_Free/main/header_fixfree.js, timeout=120

[MITM]
hostname = api.revenuecat.com, raw.githubusercontent.com
